enum ACTION_TYPE {
	SET_MODE = 'SET_MODE',
	SET_STATE = 'SET_STATE',
	INTRODUCTION = 'INTRODUCTION',
	ERROR = 'ERROR',
	REQUEST_PREVIEW = 'REQUEST_PREVIEW',
	STREAM = 'STREAM'
}

export default ACTION_TYPE;
